-- Inserir todas as pedras de evolução com sprites da PokeAPI
INSERT INTO public.items (name, description, type, price, icon_url) VALUES
  ('Fire Stone', 'Pedra que evolui Pokémon do tipo Fogo', 'evolution_stone', 2500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fire-stone.png'),
  ('Water Stone', 'Pedra que evolui Pokémon do tipo Água', 'evolution_stone', 2500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/water-stone.png'),
  ('Thunder Stone', 'Pedra que evolui Pokémon do tipo Elétrico', 'evolution_stone', 2500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/thunder-stone.png'),
  ('Leaf Stone', 'Pedra que evolui Pokémon do tipo Planta', 'evolution_stone', 2500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leaf-stone.png'),
  ('Moon Stone', 'Pedra que evolui certos Pokémon sob luz da lua', 'evolution_stone', 2500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/moon-stone.png'),
  ('Sun Stone', 'Pedra que evolui certos Pokémon sob luz do sol', 'evolution_stone', 2500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sun-stone.png'),
  ('Shiny Stone', 'Pedra brilhante que evolui certos Pokémon', 'evolution_stone', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/shiny-stone.png'),
  ('Dusk Stone', 'Pedra sombria que evolui certos Pokémon', 'evolution_stone', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dusk-stone.png'),
  ('Dawn Stone', 'Pedra que brilha ao amanhecer', 'evolution_stone', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dawn-stone.png'),
  ('Ice Stone', 'Pedra gelada que evolui Pokémon do tipo Gelo', 'evolution_stone', 2500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ice-stone.png'),
  ('Oval Stone', 'Pedra oval que evolui Happiny quando segurada', 'evolution_stone', 2000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/oval-stone.png'),
  ('Kings Rock', 'Objeto que evolui Poliwhirl e Slowpoke ao trocar', 'evolution_item', 3500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/kings-rock.png'),
  ('Metal Coat', 'Revestimento metálico que evolui Onix e Scyther', 'evolution_item', 3500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/metal-coat.png'),
  ('Dragon Scale', 'Escama de dragão que evolui Seadra ao trocar', 'evolution_item', 3500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dragon-scale.png'),
  ('Up-Grade', 'Dispositivo que evolui Porygon ao trocar', 'evolution_item', 3500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/up-grade.png'),
  ('Dubious Disc', 'Disco duvidoso que evolui Porygon2 ao trocar', 'evolution_item', 4000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dubious-disc.png'),
  ('Protector', 'Protetor que evolui Rhydon ao trocar', 'evolution_item', 4000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/protector.png'),
  ('Electirizer', 'Dispositivo que evolui Electabuzz ao trocar', 'evolution_item', 4000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/electirizer.png'),
  ('Magmarizer', 'Dispositivo que evolui Magmar ao trocar', 'evolution_item', 4000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/magmarizer.png'),
  ('Reaper Cloth', 'Tecido que evolui Dusclops ao trocar', 'evolution_item', 4000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/reaper-cloth.png'),
  ('Prism Scale', 'Escama prismática que evolui Feebas ao trocar', 'evolution_item', 3500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/prism-scale.png'),
  ('Deep Sea Tooth', 'Dente do mar que evolui Clamperl em Huntail', 'evolution_item', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/deep-sea-tooth.png'),
  ('Deep Sea Scale', 'Escama do mar que evolui Clamperl em Gorebyss', 'evolution_item', 3000, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/deep-sea-scale.png'),
  ('Razor Claw', 'Garra afiada que evolui Sneasel à noite', 'evolution_item', 3500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/razor-claw.png'),
  ('Razor Fang', 'Presa afiada que evolui Gligar à noite', 'evolution_item', 3500, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/razor-fang.png');
